### PR TITLE
Update GitHub workflow

### PR DESCRIPTION
**Pull request by uklotzde**
Please see the individual commits for details.

~~@ruabmbua You probably forgot to update the workflow triggers from `master` to `main`. See the first commit.~~ Obsolete

### CODE REVIEW

**Comment by uklotzde** [comment]
The hidapi/libusb post-build cleanup does not seem to work as expected. I will remove it for now.

**Comment by uklotzde** [comment]
The TODO is fixed now. The cleanup after the build step was missing.

**Comment by ruabmbua** [comment]
Thx for improving our CI! Unfortunately I am a bit too busy the next few days, so I will not be able to review until next week probably.

**Review by ruabmbua — APPROVED** [review]
Ok LGTM, thanks!

**Pull request merged**
