### PR TITLE
hiddevice: add `AsFd` impl

### PR DESCRIPTION
**Pull request by JohannesSchilling**
This is useful to allow performing custom ioctls/operations on nonstandard HID devices.

### CODE REVIEW

**Comment by ruabmbua** [comment]
Its probably better to impl https://doc.rust-lang.org/std/os/fd/trait.AsFd.html ?

**Comment by ruabmbua** [comment]
Also, would you mind looking into if we can do the same for the rust windows backend?

**Comment by JohannesSchilling** [comment]
hm, on first look windows looks more difficult, because there we use https://docs.rs/windows-sys/latest/windows_sys/Win32/Foundation/type.HANDLE.html as basis, but the [`AsHandle` trait](https://doc.rust-lang.org/std/os/windows/io/trait.AsHandle.html) uses https://doc.rust-lang.org/std/os/windows/io/type.RawHandle.html, so we'd have to cast `isize` to `*mut c_void` (?)

**Comment by ruabmbua** [comment]
I say lets ignore windows for now. I looked through some comments e.g. https://github.com/microsoft/windows-rs/issues/2222. If windows_sys devs decide to implement something, we can use that.

**Comment by ruabmbua** [comment]
Seems like your changes do not compile, pls check.

**Comment by ruabmbua** [comment]
Thx, will release a new version to crates.io soon.

**Pull request merged**
