### PR TITLE
Fixed issue #5 & some minor changes

### PR DESCRIPTION
**Pull request by ruabmbua**
This fixes the bug in issue #5 without breaking API compatibility.

Also some minor changes here and there like updating doc & fixing doc.rs link.

@r8d8 could you please test it with 0 devices, I struggle at removing all hid devices (is a builtin kernel module, and my laptop has some integrated hid peripherals).

Edit: Although I am almost sure it will work.

### CODE REVIEW

**Comment by r8d8** [comment]
Yeap, offcourse

**Comment by r8d8** [comment]
Side question: I was thinking that all laptops should have at least 1 HID device(keyboard), or it is implemented in other way?

**Comment by ruabmbua** [comment]
Not really (mine uses HID for the keyboard lights, and PS/2 for keyboard)

I am almost sure there are some without any HID devices.

**Comment by r8d8** [comment]
@ruabmbua it works, no Seq Faults

**Comment by ruabmbua** [comment]
Ping @Osspial , could you please review & publish.

**Comment by Osspial** [comment]
Looks good, publishing now.

**Pull request merged**
